language: java

script:
        gradle jar

before_deploy:
      - export RELEASE_JAR_FILES=$(find $TRAVIS_BUILD_DIR/build/libs/ -name "*.jar")
      - echo "Deploying $RELEASE_JAR_FILES to GitHub releases..."

deploy:
        provider: releases
        api_key: "$GH_TOKEN"
        file_glob: true
        file: "$RELEASE_JAR_FILES"
        skip_cleanup: true
        on:
                tags: true
